# Generated by Django 3.1.4 on 2020-12-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(db_index=True, max_length=100)),
                ('std_rollno', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('address', models.TextField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('std_entry', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-std_name',),
            },
        ),
    ]
